name: API Upload

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ğŸ¤‘ Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: ğŸ¤‘ Cache Cargo Lambda
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/cargo-lambda
          key: cargo-lambda

      - name: âš¡ Install Zig
        uses: mlugg/setup-zig@v2

      - name: ğŸ“¦ Package Lambda Function
        run: |
          cargo install cargo-lambda
          cargo lambda build --release --arm64 --output-format zip
        working-directory: backend

      - name: ğŸ”‘ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ğŸª£ Update Lambda Code
        run: |
          aws s3 cp backend/target/lambda/my_crate/bootstrap.zip s3://flashcards-bootstrap-bin/bootstrap.zip

      - name: ğŸ—ï¸ Terraform Apply
        run: |
          terraform init
          terraform plan -out=tfplan
            terraform apply -auto-approve tfplan
        working-directory: terraform
