name: API Upload

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ğŸ¤‘ Cache Cargo registry & build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: ğŸ¤‘ Cache Cargo Lambda binary
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/cargo-lambda
          key: cargo-lambda-v1

      - name: âš¡ Install Zig
        uses: mlugg/setup-zig@v2

      - name: ğŸ“¦ Install cargo-lambda if missing
        run: |
          if ! command -v cargo-lambda &> /dev/null; then
            cargo install cargo-lambda
          fi

      - name: ğŸ“¦ Package Lambda Function
        run: |
          cargo lambda build --release --arm64 --output-format zip
        working-directory: backend

      - name: ğŸ”‘ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ğŸª£ Update Lambda Code
        run: |
          aws s3 cp backend/target/lambda/backend/bootstrap.zip s3://flashcards-bootstrap-bin/bootstrap.zip

      - name: ğŸ—ï¸ Terraform Apply
        run: |
          terraform init
          terraform plan -out=tfplan
            terraform apply -auto-approve tfplan
        working-directory: terraform
